def findPal(s):
	t = s.replace('A','t').replace('T','a').replace('G','c').replace('C','g').upper()
	print s
	print t
	l = 4
	S = []
	while l <= 12:
		for i in range(len(s)):
			tt = t[i:i+l]
			if s[i:i+l] == tt[::-1] and len(tt) == l:
				S.append((i,l))#,len(s)-i))
		l += 1		
	for p, l in S:
		print p+1, l

findPal('GCGCGGCAGTCTTCCCTCGAGATCGCCACGAGTTAATTACACTCAACATAGTTTTGTCTCAGCAACTCCGACGCAGTATAGCTAGATTATTGACTAAACATATTAAGTACGGGACGCCATAACGGTACGCTCTTCACTGAATTTTGTCACTGCGGCGTAAAACCCAGCGCTTGTTAGGATAATAGTGGGAAACTACACACCTACCAGCAAACCGCTTATACTCACCAAACGCATGGGAATGCGCACTCTTAATACGCCGCTCGTCTGGCGGTAGAACGCTATATACAGGTAAAATCGTGCACCAGAATGTCAATGGAATACCGTCTTCTTGGTAAGAGCTAGCTCCCCATGTAGATGTGGCGGTTACTACTGGCGAGCTGGGTCAGGACTGCTTTACATCTGTGTTTCCTAGGAAATGGCTTGCGGCAATAGAAGCTCGCACGAACGAGTTTCTTAGGATCCTAATCGAGCCTCGCCAAGAACTTTGTCATTACGGTAGCCCCTACATTTACTATGTGTTTTAGTTAATCTCCTGCCCGGCCAATATCGTCTACACTGCCCCGCCCGCTACGCGAAGATGGCCTACACGGTATAAGCGTGCTTATCGTGCTCGTGCTTCACGGGACCCCTACTATTGTCACTTTTTTGCACGCAAGGAGCCCTTTGGCACCTCGTGTCTCACTATATATACTGGGATTGGTAGTTCTAGTAGTGGTACACCCCCCTCCTTCTGGTCACATCGCGCTGCTTTATCGTGGCATTAGAGTCGTCCGGGTCGATCCATCAACCTGGTACCCCGGTTAGAACTCGGCGCGTATAT')
